# Generated by Django 3.2.6 on 2021-08-11 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='critics',
            field=models.ManyToManyField(related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
